CREATE TYPE GAME_STATUS AS ENUM ('ANNOUNCED', 'BET_SUBMISSION', 'IN_PROGRESS', 'SUSPENDED', 'ARCHIVED');

CREATE TABLE IF NOT EXISTS game (
    id SERIAL,
    min_bet_amount BIGINT NOT NULL,
    max_bet_amount BIGINT NOT NULL,
    status GAME_STATUS DEFAULT 'ANNOUNCED',
    PRIMARY KEY(id)
);

INSERT INTO game(id, min_bet_amount, max_bet_amount, status)
VALUES
(1, 100, 1000, 'ANNOUNCED'),
(2, 50, 500, 'BET_SUBMISSION'),
(3, 400, 800, 'BET_SUBMISSION'),
(4, 500, 1000, 'IN_PROGRESS'),
(5, 500, 1000, 'SUSPENDED'),
(6, 1000, 2000, 'ARCHIVED');
